apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: 2 # base-0 so '3' means 4 revisions
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        version: {{ .Values.imageVersion }}
    spec:
      containers:
      - name: frontend
        image: {{ .Values.acrUrl }}/aspire-vue:{{ .Values.imageVersion }} # or aspire-vue or aspire-react or aspire-blazor
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
          requests:
            memory: "32Mi"
            cpu: "50m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
